# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
        . ~/.bashrc
fi

# User specific environment and startup programs

# path to vagrant scripts
export PATH=/vagrant/scripts:$PATH

for script in ~/.bash_profile_rc/*.sh
do
    echo "Setup profile: $script"
    . $script
done ;
